#port
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 100
  servlet:
    context-path: /
#spring resource
spring:
  datasource:
    url: jdbc:mysql:///ladmin?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    cache: false
    spring:
  resources:
    static-locations: classpath:/static/,  classpath:/templates/pages/
  task:
    execution:
       pool:
         core-size: 5
         max-size: 128
         queue-capacity: 128
         keep-alive: 6000
         thread-name-perfix: db-service-task-
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
  
mybatis:

  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml
  
#log
logging:
  level:
   com.ladmin: debug
    